### ISSUE TITLE
bug: No sensor visuals in the robot 

### ISSUE THREAD

**Issue by danlee1213** [HKUST-Robocon/Emulator-Release#1]
**Describe the bug**
In the updated emulator (v 1.0.2), the sensor visuals, which are colored circles, are just disappeared. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72503871/99148159-2e2a4d80-26c1-11eb-83cb-65a046c15071.png)
Above is the original robot sensor visuals in the previous emulator

![image](https://user-images.githubusercontent.com/72503871/99148175-4b5f1c00-26c1-11eb-9138-b726d805a84f.png)
No sensor visuals in the recent(1.0.2) emulator.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by TrebledJ** [comment]
Yes, this has been listed in the release page as an improvement so that unused sensors don't clutter the screen. They'll be drawn the moment the simulation begins, after pressing Play. Hope this clarifies any confusion.
